# TUGAS 5

## 5.16 List 2 Dimensi

In [1]:
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#MEMBUAT LIST 2 DIMENSI

#List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.
#list dua dimensi ini diibaratkan seperti tabel, terdiri dari baris dan kolom sehingga penggambarannya seperti sebuah matriks.

#contoh 1
#inisialisasi variabel matrik
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
]
print('tampilkan nilai variabel matrik : ', matrik)
#pada contoh 1, baris pertama diisi oleh data 1,2,3,4. Baris kedua diisi oleh data 5,6,7,8
#Baris ketiga diisi oleh data 9,10,11,12. dan baris keempat diisi oleh data 13,14,15,16.

#______________________________________________________________________________________________________________________________

#CARA MENGAMBIL DATA DARI DALAM LIST
#Pengurutan indeks dimulai dari 0 untuk baris.
#Sehingga, data baris ke 1 berada pada indeks ke 0,  data baris ke 2 berada pada indeks ke 1, dan begitu seterusnya.
#Hal yang sama juga diterapkan pada kolom.
#Jadi kalau kita ingin mengambil data baris ke 3, maka kita mengambil data yang ada pada indeks ke 2
print('Data baris ketiga : ', matrik[2])

#kalau kita ingin mengambil data baris ke 2 dan kolom ke 3, berarti kita ambil indeks baris ke 1 dan indeks kolom ke 2
print('Data baris ke 2 dan kolom ke 3 : ', matrik[1][2])
print('\n')

#______________________________________________________________________________________________________________________________
#PROGRAM MENAMPILKAN LIST DALAM BENTUK MATRIKS
print('List Dalam Bentuk Matriks')
for a in matrik:
#a merupakan semua elemen pada matrik
    for b in a:
    #b akan merepresentasikan setiap elemen pada a
        print(b,end = " ")
        #seluruh anggota pada b di print dengan menambahkan spasi dibelakangnya
    print()
    
#______________________________________________________________________________________________________________________________  
#PROGRAM UNTUK MENAMBAHKAN DATA PADA LIST
#kita coba menambahkan/menyelipkan data pada baris ketiga matrik dengan angka 17,18,19,20
matrik.insert(2, [17,18,19,20])
print('\nOutput Menambahkan Data Pada List :')
for a in matrik:
    for b in a:
        print(b, end = " ")
    print()
    
#______________________________________________________________________________________________________________________________
#PROGRAM MENGGANTI NILAI PADA LIST
#kita coba ganti angka 9 pada baris keempat dengan angka 21
matrik[3][0] = 21
#kita ganti semua data pada baris pertama dengan data yang baru
matrik[0] = [22,23,24,25]
#kita ganti semua data pada baris kedua dengan data yang baru
matrik[1] = [26,27,28,29]
print('\nOutput Program Mengganti Nilai List :')
for a in matrik:
    for b in a:
        print(b, end = " ")
    print()
    
#______________________________________________________________________________________________________________________________
#PROGRAM MENGHAPUS ELEMEN DALAM LIST
#kita bisa menghapus elemen tertentu pada list. 
#kita coba untuk menghapus semua elemen pada baris keempat
del matrik[3]
print('\nOutput Menghapus Elemen dalam List :')
for a in matrik:
    for b in a:
        print(b, end = " ")
    print()
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

tampilkan nilai variabel matrik :  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
Data baris ketiga :  [9, 10, 11, 12]
Data baris ke 2 dan kolom ke 3 :  7


List Dalam Bentuk Matriks
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 

Output Menambahkan Data Pada List :
1 2 3 4 
5 6 7 8 
17 18 19 20 
9 10 11 12 
13 14 15 16 

Output Program Mengganti Nilai List :
22 23 24 25 
26 27 28 29 
17 18 19 20 
21 10 11 12 
13 14 15 16 

Output Menghapus Elemen dalam List :
22 23 24 25 
26 27 28 29 
17 18 19 20 
13 14 15 16 


## 5.17 Tuples

In [2]:
#Tuples adalah urutan objek yang tidak dapat dirubah isinya. 
#Tupel menggunakan tanda kurung, sedangkan List Python menggunakan tanda kurung siku.

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#CONTOH PEMBUATAN TUPLES
a = ()
b = (50,)
c = ("Perempuan", 18, 2004, "Matematika")
d = (22, 23, 24, 25, 26)
e = 'Gunggek', 'Wanda', 'Tya', 'Marsanda'

#Tuples kosong ditulis dengan dua tanda kurung yang tidak berisi apa-apa. contoh a = ()
#Untuk menulis tuples yang hanya berisi satu nilai, kita harus tetap memasukkan koma.
#jika tanpa koma, output dari variabel b akan berbeda. output variabel b tanpa koma akan menjadi : 50 saja tanpa kurung

print(a)
print(b)
print(c)
print(d)
print(e)
print('\n')

#_______________________________________________________________________________________________________________________________
#CARA MENGAKSES NILAI DALAM TUPLES
#untuk mengakses nilai dalam tuples, gunakan tanda kurung siku untuk memanggil indeks dan mendapatkan nilai dari indeks tersebut
print('Mengakses Nilai dalam Tuples')
print('c[3]   : ', c[3])
print('e[0:4] : ', e[0:4])
print('\n')

#_______________________________________________________________________________________________________________________________
#UPDATE NILAI DALAM TUPLES
#nilai tuples tidak dapat diubah, tetapi kita bisa mengambil bagian dari tuples yang ada untuk membuat tuples baru
print('Update Nilai dalam Tuples')
nama = ('Wanda', 'Paramitha')
nim = (22, 100)
#kita tidak bisa membuat program seperti nim[0] = 100 karena memang nilai pada tuple tidak bisa dirubah
#tapi kita bisa membuat tuple baru dengan menjalankan program sebagai berikut
saya = nama + nim
print('Nama dan Nim : ', saya)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

()
(50,)
('Perempuan', 18, 2004, 'Matematika')
(22, 23, 24, 25, 26)
('Gunggek', 'Wanda', 'Tya', 'Marsanda')


Mengakses Nilai dalam Tuples
c[3]   :  Matematika
e[0:4] :  ('Gunggek', 'Wanda', 'Tya', 'Marsanda')


Update Nilai dalam Tuples
Nama dan Nim :  ('Wanda', 'Paramitha', 22, 100)


In [3]:
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#CONTOH PROGRAM PADA TUPLES
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#inisialisasi variabel tuples
angka = (7, 14, 21, 28, 35)
print(angka)
#menggunakan operator + untuk menggabungkan elemen dan menciptakan tuples baru
angka = angka + (42, 49)
print(angka)
#menambahkan item dengan indeks tertentu
angka = angka[0:5] + (36, 37, 38, 39, 40, 41) + angka[5:]
print(angka)
#mengubah tuple menjadi list
list_angka = list(angka)
#menambahkan item pada list
list_angka.append(50)
angka = tuple(list_angka)
print(angka)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

(7, 14, 21, 28, 35)
(7, 14, 21, 28, 35, 42, 49)
(7, 14, 21, 28, 35, 36, 37, 38, 39, 40, 41, 42, 49)
(7, 14, 21, 28, 35, 36, 37, 38, 39, 40, 41, 42, 49, 50)


## 5.18 Dictionaries

In [4]:
#Dictionaries digunakan jika datanya terkait satu sama lain.
#Urutan dictionaries berisi key dan value dimana keduanya dipisahkan oleh titik dua (:), 
#item dipisahkan oleh koma, dan semuanya tertutup dalam kurung kurawal.
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#CONTOH PENGGUNAAN DICTIONARIES

#inisialisasi data pada dictionaries
data_orang = {
    'nama'   : "Wanda Paramitha",
    'umur'   : 18,
    'apakah perempuan' : True 
}
#untuk mengakses dictionaries, kita harus menggunakan tanda kurung siku untuk mendapatkan nilainya
print('Nama  : ', data_orang['nama'])
print('Umur  : ', data_orang['umur'])
print('Apakah', data_orang['nama'], 'perempuan? ', data_orang['apakah perempuan'])
print()

#_______________________________________________________________________________________________________________________________
#UPDATE NILAI DALAM DICTIONARIES
#kita dapat menambahkan entri baru pada dictionaries
data_orang['alamat'] = 'Bangli'
data_orang['lahir'] = 'Agustus'

print(data_orang.get('nama'), 'berasal dari', data_orang.get('alamat'), 'dan lahir pada bulan', data_orang.get('lahir'), '\n')

#_______________________________________________________________________________________________________________________________
#PROGRAM MERUBAH ANGKA NIM MENJADI SEBUTAN BILANGAN

angka = {
    '0' : 'nol',   '1' : 'satu',  '2' : 'dua',    '3' : 'tiga',     '4' : 'empat',
    '5' : 'lima',  '6' : 'enam',  '7' : 'tujuh',  '8' : 'delapan',  '9' : 'sembilan'
}

NIM = input('Masukkan NIM Anda : ')
NIM_Saya = ""
for isi in NIM:
    NIM_Saya += angka.get(isi) + " "
print(NIM_Saya)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Nama  :  Wanda Paramitha
Umur  :  18
Apakah Wanda Paramitha perempuan?  True

Wanda Paramitha berasal dari Bangli dan lahir pada bulan Agustus 

Masukkan NIM Anda : 2208541022
dua dua nol delapan lima empat satu nol dua dua 


## 5.19 Fungsi dalam Python

In [5]:
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#PENGAPLIKASIAN FUNGSI DALAM PYTHON
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#PROGRAM MENGHITUNG WAKTU TEMPUH SUATU PERJALANAN
def waktu_tempuh(jarak, kecepatan):
    waktu = jarak/kecepatan
    return waktu
x = waktu_tempuh(80, 60)
print('Jika diketahui jarak suatu tempat adalah 80km dengan kecepatan pengendara adalah 60km/jam')
print('Maka waktu tempuh kendaraan tersebut adalah ', x , "jam")
print('\n')

#_______________________________________________________________________________________________________________________________
#PROGRAM MENGHITUNG LUAS BANGUN DATAR SEGITIGA, PERSEGI, PERSEGI PANJANG, ATAU LINGKARAN

#rumus luas tiap bangun datar
def luas_segitiga(alas, tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = 3.14*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegipanjang(panjang, lebar):
    luas = panjang*lebar
    return luas

jenis_bidang = input('Jenis Bidang : ')
if jenis_bidang == 'Segitiga':
    alas   = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas   = luas_segitiga(alas, tinggi)
    print(f"Luas {jenis_bidang} yang mempunyai alas {alas} dan tinggi {tingi} adalah {luas}")
elif jenis_bidang == "Lingkaran":
    jari_jari = float(input('Berpakah panjang jari-jarinya? '))
    luas      = luas_lingkaran(jari_jari)
    print(f'Luas {jenis_bidang} yang mempunyai jari-jari {jari_jari} adalah {luas}')
elif jenis_bidang == "Persegi":
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} yang mempunyai panjang sisi {sisi} adalah {luas}")
elif jenis_bidang == "Persegi Panjang":
    panjang = float(input('Berapakah panjangnya? '))
    lebar   = float(input('Berpakah lebarnya? '))
    luas    = luas_persegipanjang(panjang, lebar)
    print(f"Luas {jenis_bidang} yang mempunyai panjang {panjang} dan lebar {lebar} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak tersedia.")
    print(f"Silahkan pilih Segitiga, Lingkaran, Persegi, atau Persegi Panjang")
    print('Terimakasih')
print('\n')

#_______________________________________________________________________________________________________________________________
#PROGRAM MENGHITUNG LUAS PERMUKAAN DAN VOLUME BALOK

#Menginput Panjang, Lebar, dan Tinggi Balok
p = int(input('Masukkan Panjang Balok: '))
l = int(input('Masukkan Lebar Balok: '))
t = int(input('Masukkan Tinggi Balok: '))
#Hitung Luas Permukaan
def luas_permukaan(p,l,t):
    L = 2*((p*l)+(p*t)+(l*t))
    return L
#Hitung Volume Balok
def volume(p,l,t):
    V = p*l*t
    return V
print('Jadi balok dengan ukuran panjang: {}, lebar: {}, tinggi: {}'.format(p,l,t)) 
print('Mempunyai luas permukaan: {} dan volume: {} '.format(luas_permukaan(p,l,t), volume(p,l,t)))

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Jika diketahui jarak suatu tempat adalah 80km dengan kecepatan pengendara adalah 60km/jam
Maka waktu tempuh kendaraan tersebut adalah  1.3333333333333333 jam


Jenis Bidang : Lingkaran
Berpakah panjang jari-jarinya? 10
Luas Lingkaran yang mempunyai jari-jari 10.0 adalah 314.0


Masukkan Panjang Balok: 10
Masukkan Lebar Balok: 8
Masukkan Tinggi Balok: 5
Jadi balok dengan ukuran panjang: 10, lebar: 8, tinggi: 5
Mempunyai luas permukaan: 340 dan volume: 400 


## 5.20 Numpy

### 5.20.1 Perintah Dasar pada Numpy

In [6]:
#Numpy harus kita impor dulu agar bisa digunakan di dalam program.
import numpy as np

#MEMBUAT ARRAY DENGAN NUMPY
a = np.array([0,1,2,3,4])
print('Data pada array(a) terdiri dari : ', a)
#Pada contoh ini kita membuat matriks dengan list.
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print('Data pada array(b) terdiri dari : \n', b)
print()

#MENGHITUNG JUMLAH DIMENSI
#Untuk mengetahui jumlah dimensi pada data kita bisa menggunakan fungsi 'ndim'
#cek jumlah dimensi pada array(a)
print('jumlah dimensi pada data array(a) adalah ', a.ndim)
#cek jumlah dimensi pada array(b)
print('jumlah dimensi pada data array(b) adalah ', b.ndim)
print()

#ARRAY SHAPE
#Pada fungsi shape menghasilkan sebuah tuple yang berisikan panjang sebuah array pada tiap dimensi
#cek shape dari array(a)
print('Array(a) memiliki shape', a.shape, 'yaitu panjang array pada', a.ndim, 'dimensi array')
#cek shape dari array(b)
print('Array(b) memiliki shape', b.shape, 'yaitu panjang array pada', b.ndim, 'dimensi array')

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Data pada array(a) terdiri dari :  [0 1 2 3 4]
Data pada array(b) terdiri dari : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

jumlah dimensi pada data array(a) adalah  1
jumlah dimensi pada data array(b) adalah  2

Array(a) memiliki shape (5,) yaitu panjang array pada 1 dimensi array
Array(b) memiliki shape (3, 3) yaitu panjang array pada 2 dimensi array


### 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [7]:
#Indeks pada suatu array dimulai pada indeks ke-0.
#Untuk mengakses elemen pada array, kita menggunakan indeks sebagai alamat elemen pada array

d = np.array ([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])
print("Data pada array(d) terdiri dari: ")
print(d)
print()

#mengakses elemen pada indeks
print('Elemen d yang berada pada indeks ke-0 adalah : ', d[0])
print('Elemen d yang berada pada baris pertama kolom keempat adalah : ', d[0,3])
print('Elemen d yang berada pada baris kedua dari setiap kolom adalah : ', d[1, :])
print('Elemen d yang berada pada kolom ketiga dari setiap baris adalah : ', d[:,2])
print()

#Kita dapat melakukan assign nilai baru pada suatu elemen berdasarkan alamat indeksnya.
#Maka setelah dilakukan assign, nilai elemen pada indeks akan berganti dengan elemen yang baru.
d[0] = [1,0,0,0]
print('Data pada array(d) setelah diganti elemennya : ')
print(d)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Data pada array(d) terdiri dari: 
[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]

Elemen d yang berada pada indeks ke-0 adalah :  [1 2 3 4]
Elemen d yang berada pada baris pertama kolom keempat adalah :  4
Elemen d yang berada pada baris kedua dari setiap kolom adalah :  [5 6 7 8]
Elemen d yang berada pada kolom ketiga dari setiap baris adalah :  [3 7 7 3]

Data pada array(d) setelah diganti elemennya : 
[[1 0 0 0]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]


### 5.20.3 Matrix pada Numpy

In [8]:
#Inisialisasi variabel matriks dengan fungsi ones((,))
#fungsi ones((,)) digunakan untuk mencetak matrik dengan entri 1
a = np.ones((2,3))
print('Matrik (2x3) dengan seluruh entrinya adalah 1 : ')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi zeros((,))
#fungsi zeros((,)) digunakan untuk mencetak matrik dengan entri 0
a = np.zeros((3,2))
print('Matrik (3x2) dengan seluruh entrinya adalah 0 : ')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi identity()
#fungsi identity() digunakan untuk mencetak matrik identitas
a = np.identity(4)
print('Matrik identitas dengan ordo (4x4) : ')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi ones((, , ,))
#fungsi ones((, , ,)) digunakan untuk mencetak matrik dengan entri 1 
#((, , ,)) digunakan untuk mencetak beberapa array, baris array, dan kolom array sesuai dengan variabel yang dideklarasikan
a = np.ones((2,3,4))
print('2 data array Matrik (3x4) dengan seluruh entrinya adalah 1 :')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi full((,),)
#fungsi full((,),) digunakan untuk mencetak matrik dengan entri yang sama
#fungsi ((,),) digunakan untuk mencetak ordo dan data entri sesuai dengan variabel yang dideklarasikan
a = np.full((3,2),9)
print('Matrik (3x2) dengan seluruh entrinya adalah 9 :')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi random.rand(,)
#fungsi random.rand(,) digunakan untuk mencetak matrik dengan entri random yang nilainya dapat berubah setiap kali dijalankan
a = np.random.rand(4,3)
print('Matrik (4x3) dengan seluruh isinya adalah bilangan acak (random) : ')
print(a)
print()

#Inisialisasi variabel matriks dengan fungsi random.randint(, , size = (,))
#fungsi ini digunakan untuk mencetak matrik dengan entri random yang nilainya dapat berubah-ubah
#perbedaan fungsi ini dengan fungsi random.rand(,) adalah bahwa kita bisa menentukan batasan nilainya
#(, ,) digunakan untuk menentukan batas dan (size = (,)) digunakan untuk membentuk ordo
a = np.random.randint(1,10, size = (3,4))
print('Matrik (3x4) dengan seluruh isinya adalah bilangan random dari 1-10 :')
print(a)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Matrik (2x3) dengan seluruh entrinya adalah 1 : 
[[1. 1. 1.]
 [1. 1. 1.]]

Matrik (3x2) dengan seluruh entrinya adalah 0 : 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Matrik identitas dengan ordo (4x4) : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

2 data array Matrik (3x4) dengan seluruh entrinya adalah 1 :
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Matrik (3x2) dengan seluruh entrinya adalah 9 :
[[9 9]
 [9 9]
 [9 9]]

Matrik (4x3) dengan seluruh isinya adalah bilangan acak (random) : 
[[0.59571245 0.56829318 0.10474256]
 [0.58818765 0.2968738  0.41406029]
 [0.50097211 0.3677572  0.88924315]
 [0.38294211 0.16497769 0.89902942]]

Matrik (3x4) dengan seluruh isinya adalah bilangan random dari 1-10 :
[[3 4 1 6]
 [2 4 4 4]
 [7 6 1 7]]


### 5.20.4 Copy pada Numpy

In [9]:
#Inisialisasi variabel array
a = np.array([1,2,3,4,5])
print(a)
#Pendeklarasian bahwa b=a, artinya nilai dari b akan sama dengan a
b = a
print(b)
#kode ini akan merubah nilai 1 menjadi 10
b[0] = 10
print(b)
#karena b = a, maka perubahan yang dilakukan pada variabel b juga akan mempengaruhi variabel a 
print(a)
print()


#Inisialisasi variabel baru
c = np.array([2,4,6,8])
print(c)
#variabel akan disalin dengan fungsi copy() dan akan ditempel pada variabel d
d = c.copy()
print(d)
#output dari d akan sama dengan c karena d merupakan salinan dari variabel c
print()

#kode ini akan merubah nilai 2 menjadi 10
d[0] = 10
print(d)
#Walaupun nilai pertama dari variabel d sudah diganti, tetapi hal itu tidak mempengaruhi nilai dari variabel c
print(c)
#Hal ini terjadi karena copy memiliki data dan perubahan apapun yang dilakukan pada copy tidak akan mempengaruhi array asli,
#dan perubahan apapun yang dibuat pada array asli tidak akan mempengaruhi copy.

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]
[10  2  3  4  5]

[2 4 6 8]
[2 4 6 8]

[10  4  6  8]
[2 4 6 8]


### 5.20.5 Operasi Matematika pada Numpy

In [10]:
#Inisialisasi variabel dengan fungsi array
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Diketahui data array sebagai berikut :")
print('a =', a)
print('b =', b)
print()

#OPERASI MATEMATIKA PADA 1 VARIABEL ARRAY
print('Operasi Matematika a+2 = ', a+2)
print('Operasi Matematika a-2 = ', a-2)
print('Operasi Matematika b*2 = ', b*2)
print('Operasi Matematika b/2 = ', b/2)
print('Operasi Matematika a**2 = ', a**2)
print()

#OPERASI MATEMATIKA PADA 2 VARIABEL ARRAY
print('Nilai dari a+b = ', a+b)
print('Nilai dari a-b = ', a-b)
print('Nilai dari a*b = ', a*b)
print('Nilai dari a/b = ', a/b)
print('Nilai dari b**a = ', b**a)
print()

#OPERASI TRIGONOMETRI PADA ARRAY
print('Nilai dari cos(a) = ', np.cos(a))
print('Nilai dari sin(b) = ', np.sin(b))
print('Nilai dari tan(a) = ', np.tan(a))
print('Nilai dari cosh(b) = ', np.cosh(b))
print('Nilai dari sinh(a) = ', np.sinh(a))
print('Nilai dari tanh(b) = ', np.tanh(b))
print('Nilai dari akar kuadrat a = ', np.sqrt(a))

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Diketahui data array sebagai berikut :
a = [1 2 3]
b = [4 5 6]

Operasi Matematika a+2 =  [3 4 5]
Operasi Matematika a-2 =  [-1  0  1]
Operasi Matematika b*2 =  [ 8 10 12]
Operasi Matematika b/2 =  [2.  2.5 3. ]
Operasi Matematika a**2 =  [1 4 9]

Nilai dari a+b =  [5 7 9]
Nilai dari a-b =  [-3 -3 -3]
Nilai dari a*b =  [ 4 10 18]
Nilai dari a/b =  [0.25 0.4  0.5 ]
Nilai dari b**a =  [  4  25 216]

Nilai dari cos(a) =  [ 0.54030231 -0.41614684 -0.9899925 ]
Nilai dari sin(b) =  [-0.7568025  -0.95892427 -0.2794155 ]
Nilai dari tan(a) =  [ 1.55740772 -2.18503986 -0.14254654]
Nilai dari cosh(b) =  [ 27.30823284  74.20994852 201.71563612]
Nilai dari sinh(a) =  [ 1.17520119  3.62686041 10.01787493]
Nilai dari tanh(b) =  [0.9993293  0.9999092  0.99998771]
Nilai dari akar kuadrat a =  [1.         1.41421356 1.73205081]


### 5.20.6 Perkalian Matrik pada Numpy

In [11]:
#Perkalian matrik pada numpy dapat menggunakan perintah matmul.
#Namun, harus diperhatikan bahwa ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan.
#Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4)

#Inisialisasi variabel matrik
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12], [13,14,15,16]])
print('Diketahui data matrik sebagai berikut :')
print('Matrik a\n', a)
print('Matrik b\n', b)
print()

#OPERASI PERKALIAN
print('Nilai dari matrik a dikalikan dengan matrik b adalah\n', a*b)
print()

#Kita tidak bisa mengalikan matrik a dengan matrik b menggunakan perintah matmul.
#hal ini dikarenakan ukuran dari matrik a dan matrik b yang tidak sesuai dengan persyaratan.

#Inisialisasi variabel matrik baru
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Ditambahkan matrik baru yaitu matrik c :')
print(c)
print()

#OPERASI PERKALIAN DENGAN PERINTAH MATMUL
d = np.matmul(a,c)
print('Nilai dari matrik a dikalikan dengan matrik c adalah\n', d)
#Pada kasus ini, perintah matmul dianggap valid dikarenakan ukuran dari matrik a dan matrik c sesuai dengan persyaratan

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output :

Diketahui data matrik sebagai berikut :
Matrik a
 [[1 2 3 4]
 [5 6 7 8]]
Matrik b
 [[ 9 10 11 12]
 [13 14 15 16]]

Nilai dari matrik a dikalikan dengan matrik b adalah
 [[  9  20  33  48]
 [ 65  84 105 128]]

Ditambahkan matrik baru yaitu matrik c :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Nilai dari matrik a dikalikan dengan matrik c adalah
 [[ 70  80  90]
 [158 184 210]]


### 5.20.7 min, max dan sum pada Numpy

In [12]:
#Inisialisasi variabel pada fungsi array
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print('Diketahui data array(a) sebagai berikut:')
print(a)
print()

#Mencari nilai minimum dari a
b = np.min(a)
print('Nilai minimum dari data array(a) adalah :', b)
#mencari nilai minimum dari baris data array
c = np.min(a, axis=0) #(axis=0) digunakan untuk mencari nilai minimum dari baris data
print('Nilai minimum dari baris pada data array(a) adalah : ', c)
#mencari nilai minimum dari kolom data array
d = np.min(a, axis=1) #(axis=1) digunakan untuk mencari nilai minimum dari kolom data
print('Nilai minimum dari kolom pada data array(a) adalah : ', d)
print()

#Mencari nilai maksimum dari data a
e = np.max(a)
print('Nilai maksimum dari data array(a) adalah : ', e)
#Mencari nilai maksimum dari baris data array
f = np.max(a, axis=0) #(axis=0) digunakan untuk mencari nilai maksimum dari baris data
print('Nilai maksimum dari baris pada data array(a) adalah : ', f)
#Mencari nilai maksimum dari kolom data array
g = np.max(a, axis=1) #(axis=1) digunakan untuk mencari nilai maksimum dari kolom data
print('Nilai maksimum dari kolom pada data array(a) adalah : ', g)
print()

#Mencari jumlah dari data array
h = np.sum(a)
print('Jumlah dari seluruh data array(a) adalah :', h)
#Mencari jumlah dari baris data array
i = np.sum(a, axis=0) #(axis=0) digunakan untuk mencari jumlah dari baris data
print('Jumlah dari seluruh baris data array(a) adalah :', i)
#Mencari jumlah dari kolom data array
j = np.sum(a, axis=1) #(axis=1) digunakan untuk mencari jumlah dari kolom data
print('Jumlah dari seluruh kolom data array(a) adalah :', j)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#output:

Diketahui data array(a) sebagai berikut:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Nilai minimum dari data array(a) adalah : 1
Nilai minimum dari baris pada data array(a) adalah :  [1 2 3 4]
Nilai minimum dari kolom pada data array(a) adalah :  [1 5 9]

Nilai maksimum dari data array(a) adalah :  12
Nilai maksimum dari baris pada data array(a) adalah :  [ 9 10 11 12]
Nilai maksimum dari kolom pada data array(a) adalah :  [ 4  8 12]

Jumlah dari seluruh data array(a) adalah : 78
Jumlah dari seluruh baris data array(a) adalah : [15 18 21 24]
Jumlah dari seluruh kolom data array(a) adalah : [10 26 42]
